### ISSUE TITLE
cannot compile with swift 5.1.2

### ISSUE THREAD

**Issue by aphuang2013** [pingidentity/pingone-customers-mobile-sdk#20]
/Users/peterahuang/workspace/pingone-customers-mobile-sdk/iOS/Sample Code/SampleApp/ViewController.swift:11:8: Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.2 compiler: /Users/peterahuang/workspace/pingone-customers-mobile-sdk/iOS/Sample Code/SampleApp/PingOne.framework/Modules/PingOne.swiftmodule/x86_64.swiftmodule

any hints is greatly appreciated

**Comment by asafd1** [comment]
Looks like you are not using the latest code. Pull the [master](https://github.com/pingidentity/pingone-customers-mobile-sdk/tree/master/) branch and you should be fine.

**Comment by aphuang2013** [comment]
ok, I was able to build with the latest master.  However, I'm a little confused by the setting,  what is this Issuer in P14C here,  can you provide more info?

**Comment by asafd1** [comment]
The environment issuer URI is: `https:​/​/​auth.​pingidentity.​com/​<environmentId>/​as`
You can find it under the Configuration tab of your Applications in the PingOne admin console.
