### ISSUE TITLE
SDK version in samples differs from the latest one

### ISSUE THREAD

**Issue by hkrop** [pingidentity/pingone-customers-mobile-sdk#22]
For example [SDK has more functions (i.e processRemoteNotificationAction)](https://github.com/pingidentity/pingone-customers-mobile-sdk/blob/master/iOS/SDK/PingOne.xcframework/ios-armv7_arm64/PingOne.framework/Modules/PingOne.swiftmodule/arm.swiftinterface) then SDK linked in [sample code](https://github.com/pingidentity/pingone-customers-mobile-sdk/blob/master/iOS/Sample%20Code/SampleApp/PingOne.xcframework/ios-armv7_arm64/PingOne.framework/Modules/PingOne.swiftmodule/arm.swiftinterface).

**Comment by asafd1** [comment]
fixed
